### ISSUE TITLE
Création de compte - erreur confirmation du mdp

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/fabrique-chatbot-front#36]
Lors de la création de compte, j'ai bien reçu le mail pour me connecter et initialiser mon mdp. Par contre, quand j'ai mis le mdp, impossible d'aller plus, car j'ai eu l'affichage d'une erreur.
<img width="1085" alt="Capture d’écran 2020-04-22 à 09 30 03" src="https://user-images.githubusercontent.com/63412351/79980049-c7361480-84a2-11ea-88c4-286c623b886e.png">

**Comment by vincentlaine** [comment]
Pas de check de password côté Front.

+ Formater proprement les erreurs
